- name: "[ADD_STORAGE] Edit /etc/my.cnf.d/server.cnf"
  blockinfile:
      content: |
        {% raw %}[mysqld]
#log-bin=mysql-bin
#binlog_format=mixed
bind-address = 127.0.0.1
        {% endraw %}
      dest: /etc/my.cnf.d/server.cnf
  tags:
    - mariadb
