  - name: "[NEOFETCH] Create folder"
    file:
      path: /root/.config/neofetch
      state: directory
      recurse: yes
    tags:
    - neofetch

  - name: "[NEOFETCH] Configuration file"
    template:
      src: ../templates/root/.config/neofetch/config.j2
      dest: /root/.config/neofetch/config
    tags:
    - neofetch
    - neofetch_config